import * as THREE from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
import { buildDomain, insidePolygons } from './scene.js';
import { mountSurveys } from './surveys/controller.js';

const $=id=>document.getElementById(id);
let data,photos,model,renderer,camera,orbit,scene,light,activeView='castle',plan=false,animation=null,selectedCode=null,volumeId=null,placing=false;
let scenario={version:1,site:'domaine-grangues-3d',wall:'existing',roof:'existing',volumes:[]};
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let toastTimer, surveys;
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
function showTab(name){if(name==='project')surveys?.toModel();document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==`panel-${name}`);document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-current',b.dataset.tab===name?'page':'false');});$('sidebar').classList.remove('closed');$('menu-toggle').setAttribute('aria-expanded','true');}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
$('menu-toggle').addEventListener('click',()=>{$('sidebar').classList.toggle('closed');$('menu-toggle').setAttribute('aria-expanded',String(!$('sidebar').classList.contains('closed')));});
if(matchMedia('(max-width:760px)').matches){$('sidebar').classList.add('closed');$('menu-toggle').setAttribute('aria-expanded','false');$('navigation-help').textContent='Un doigt : tourner · Deux doigts : zoomer / déplacer';}
function sourceHtml(){return `<p class="precision-note"><strong>Maquette de travail.</strong> Les parcelles et le relief utilisent des données géographiques. Les façades, toitures, arbres et aménagements sont des reconstitutions à affiner.</p><ul><li><strong>Périmètre :</strong> les 19 parcelles bleues de ton plan, confirmées dans cette conversation.</li><li><strong>Orientations confirmées par le propriétaire :</strong> cour anglaise au nord, terrasse au sud, jardin de buis à l’ouest vers le miroir d’eau et les dépendances, grand escalier et parking encadré de gros buis à l’est.</li><li><strong>Implantation :</strong> <a href="https://cadastre.data.gouv.fr/datasets/cadastre-etalab" target="_blank" rel="noreferrer">Cadastre Etalab / DGFiP</a>, millésime juin 2026. Surface géométrique : ${(data.area/10000).toLocaleString('fr-FR',{maximumFractionDigits:2})} ha.</li><li><strong>Relief :</strong> <a href="https://cartes.gouv.fr/aide/fr/guides-utilisateur/utiliser-les-services-de-la-geoplateforme/calcul-altimetrique/" target="_blank" rel="noreferrer">IGN RGE ALTI</a>, ${data.terrain.altitudes.length.toLocaleString('fr-FR')} points espacés de 10 m, interpolés entre les points.</li><li><strong>Sol :</strong> orthophotographie IGN, consultée le 8 septembre 2026. La date de prise de vue n’a pas été vérifiée.</li><li><strong>Bâtiments et boisements :</strong> <a href="https://www.data.gouv.fr/datasets/bd-topo-r" target="_blank" rel="noreferrer">IGN BD TOPO</a>. Les hauteurs disponibles sont indicatives et les détails des bâtiments proviennent de tes photos.</li></ul><p>La façade sud à trois travées et l’arrière en briques des dépendances sont documentés par les nouvelles photos. Les deux vues supplémentaires précisent les quatre parterres et les massifs du jardin ouest, ainsi que les gros buis du parking en graviers à l’est. L’escalier de la cour nord a été déplacé à l’extrémité opposée sur ton indication. Les dimensions, les parties encore masquées et les niveaux des terrasses demandent un contrôle. La cour anglaise nord, la terrasse sud et le passage sous le perron est sont reconstitués à partir des gros plans. Les dégagements des soupiraux visibles le long des buis sont rattachés à la façade ouest par recoupement photographique. Leur profondeur et leurs niveaux sont estimés. Le mur reliant le pavillon à la petite annexe est placé par recoupement des vues ; son tracé exact reste à confirmer. La pièce d’eau suit ici B78 ; ses berges et son niveau sont estimés.</p><p>Les données cadastrales, IGN et les photos ont des dates et des précisions différentes : un léger décalage entre le fond aérien et les constructions reste possible. Ce modèle n’est pas un relevé de géomètre.</p><p>Réutilisation des données ouvertes : Licence Ouverte / Etalab. Photographies personnelles fournies pour ce projet.</p>`;}
function loadTexture(url){return new Promise((resolve,reject)=>new THREE.TextureLoader().load(url,t=>{t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;resolve(t);},undefined,reject));}
// Procedural material swatches describe the surfaces; they do not add fictitious photographic evidence.
function materialTextures(){
 const c=document.createElement('canvas');c.width=512;c.height=512;const ctx=c.getContext('2d');let seed=53;const r=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 ctx.fillStyle='#71757a';ctx.fillRect(0,0,512,512);for(let row=0;row<32;row++)for(let col=-1;col<20;col++){const value=100+Math.floor(r()*58),x=col*28+(row%2?14:0),y=row*16;ctx.fillStyle=`rgb(${value},${value+3},${value+6})`;ctx.fillRect(x,y,27,15);ctx.fillStyle=`rgba(225,223,205,${r()*.20})`;ctx.fillRect(x+1,y+1,25,2);}
 for(let i=0;i<4500;i++){const v=140+r()*100;ctx.fillStyle=`rgba(${v},${v},${v-15},${r()*.15})`;ctx.fillRect(r()*512,r()*512,1+r()*8,1+r()*5);}
 const roof=new THREE.CanvasTexture(c);roof.wrapS=roof.wrapT=THREE.RepeatWrapping;roof.colorSpace=THREE.SRGBColorSpace;roof.anisotropy=8;
 const s=document.createElement('canvas');s.width=256;s.height=256;const sc=s.getContext('2d');sc.fillStyle='#eee9dd';sc.fillRect(0,0,256,256);for(let i=0;i<15000;i++){const v=150+r()*65;sc.fillStyle=`rgba(${v},${v},${v-5},${.06+r()*.12})`;sc.fillRect(r()*256,r()*256,1+r()*3,1+r()*3);}const stone=new THREE.CanvasTexture(s);stone.wrapS=stone.wrapT=THREE.RepeatWrapping;stone.colorSpace=THREE.SRGBColorSpace;
 const textureCanvas=()=>{const el=document.createElement('canvas');el.width=el.height=512;return el;};
 const leaf=textureCanvas(),lc=leaf.getContext('2d');lc.fillStyle='#b9c6ad';lc.fillRect(0,0,512,512);for(let i=0;i<10500;i++){const v=155+r()*100;lc.fillStyle=`rgb(${v},${Math.min(255,v+8)},${v-12})`;lc.beginPath();lc.ellipse(r()*512,r()*512,1+r()*2,1+r()*3,r()*Math.PI,0,Math.PI*2);lc.fill();}
 const grit=textureCanvas(),gc=grit.getContext('2d');gc.fillStyle='#c6c4bc';gc.fillRect(0,0,512,512);for(let i=0;i<8500;i++){const v=130+r()*118;gc.fillStyle=`rgb(${v},${v},${v-6})`;gc.beginPath();gc.ellipse(r()*512,r()*512,.6+r()*2.8,.6+r()*2.2,r()*Math.PI,0,Math.PI*2);gc.fill();}
 const paving=textureCanvas(),pc=paving.getContext('2d');pc.fillStyle='#8f9089';pc.fillRect(0,0,512,512);for(let row=0;row<24;row++)for(let col=-1;col<15;col++){const v=174+r()*72,w=512/14,h=512/24,warm=r()<.25;pc.fillStyle=warm?`rgb(${v},${v-27},${v-33})`:`rgb(${v},${v+1},${v-4})`;pc.fillRect(col*w+(row%2?w/2:0)+1,row*h+1,w-2,h-2);}
 const mapped=el=>{const t=new THREE.CanvasTexture(el);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t;};
 return {roof,roofBump:roof,stone,hedge:mapped(leaf),gravel:mapped(grit),pavers:mapped(paving)};
}
function initReferenceUi(){
 $('area').textContent=(data.area/10000).toLocaleString('fr-FR',{maximumFractionDigits:1});$('parcel-count').textContent=data.parcels.length;
 for(const p of data.parcels){const b=document.createElement('button');b.className='parcel-item';b.dataset.code=p.code;const label=document.createElement('span');label.className='parcel-code';label.textContent=p.code;const area=document.createElement('span');area.textContent=p.area<1000?Math.round(p.area).toLocaleString('fr-FR')+' m²':(p.area/10000).toLocaleString('fr-FR',{maximumFractionDigits:2})+' ha';b.append(label,area);b.addEventListener('click',()=>selectParcel(p.code,true));$('parcel-list').append(b);}
 for(const p of photos){const b=document.createElement('button');b.className='photo-card';const img=document.createElement('img');img.src='./assets/'+p.file;img.alt=p.title;img.loading='lazy';const caption=document.createElement('span');caption.textContent=p.title;b.append(img,caption);b.addEventListener('click',()=>openPhoto(p));$('photo-list').append(b);}
 $('source-details').innerHTML=sourceHtml();$('about-details').innerHTML=sourceHtml();
}
function openPhoto(p){$('photo-full').src='./assets/'+p.file;$('photo-full').alt=p.title;$('photo-title').textContent=p.title;$('photo-camera').hidden=!!p.unlocated;$('photo-camera').onclick=()=>{$('photo-dialog').close();if(model)goView(p.view);else toast('La vue 3D est indisponible sur cet appareil.');};$('photo-dialog').showModal();}
function animateCamera(position,target){if(!camera)return;plan=false;setProjectionButtons();if(reduced){camera.position.copy(position);orbit.target.copy(target);orbit.update();return;}animation={start:performance.now(),from:camera.position.clone(),to:position.clone(),tfrom:orbit.target.clone(),tto:target.clone()};}
function setProjectionButtons(){$('plan-view').classList.toggle('active',plan);$('perspective-view').classList.toggle('active',!plan);}
function goView(name){if(!model)return;surveys?.toModel();const v=model.views[name];if(!v)return;activeView=name;animateCamera(v.position,v.target);$('scene-tag').textContent=v.label;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(matchMedia('(max-width:760px)').matches){$('sidebar').classList.add('closed');$('menu-toggle').setAttribute('aria-expanded','false');}}
function selectParcel(code,fly=false){if(fly)surveys?.toModel();selectedCode=code;if(model)model.selectParcel(code);document.querySelectorAll('.parcel-item').forEach(b=>b.classList.toggle('active',b.dataset.code===code));if(!code){$('scene-tag').textContent=model?.views[activeView]?.label||'DOMAINE';return;}const p=data.parcels.find(p=>p.code===code);$('scene-tag').textContent='PARCELLE '+p.code+' · '+(p.area/10000).toLocaleString('fr-FR',{maximumFractionDigits:2})+' HA';if(fly&&model){let xs=[],zs=[];for(const poly of p.polygons)for(const [x,z] of poly[0]){xs.push(x);zs.push(z);}const radius=Math.max(40,Math.max(Math.max(...xs)-Math.min(...xs),Math.max(...zs)-Math.min(...zs))*.9);const target=new THREE.Vector3(p.center[0],model.height(...p.center),p.center[1]);animateCamera(target.clone().add(new THREE.Vector3(-radius*.4,radius*1.2,radius*.7)),target);if(matchMedia('(max-width:760px)').matches){$('sidebar').classList.add('closed');$('menu-toggle').setAttribute('aria-expanded','false');}}}
function resize(){if(!renderer||!camera)return;const el=$('viewport'),w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
function setupScene(ortho){
 scene=new THREE.Scene();scene.background=new THREE.Color(0xcad8dc);scene.fog=new THREE.FogExp2(0xcad8dc,.0004);
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('scene').append(renderer.domElement);
 const hemi=new THREE.HemisphereLight(0xe6eff5,0x7d845a,2.6);scene.add(hemi);scene.add(new THREE.AmbientLight(0xffffff,.18));
 light=new THREE.DirectionalLight(0xfff3de,3.1);light.castShadow=true;light.shadow.mapSize.set(2048,2048);light.shadow.camera.left=-125;light.shadow.camera.right=125;light.shadow.camera.top=125;light.shadow.camera.bottom=-125;light.shadow.camera.near=1;light.shadow.camera.far=650;light.shadow.bias=-.00025;light.shadow.normalBias=.18;scene.add(light,light.target);
 model=buildDomain(data,{...materialTextures(),ortho});scene.add(model.root);
 camera=new THREE.PerspectiveCamera(44,1,.25,6000);camera.position.copy(model.views.castle.position);
 orbit=new OrbitControls(camera,renderer.domElement);orbit.target.copy(model.views.castle.target);orbit.enableDamping=true;orbit.dampingFactor=.065;orbit.maxPolarAngle=Math.PI*.482;orbit.minDistance=6;orbit.maxDistance=2100;orbit.screenSpacePanning=false;orbit.maxTargetRadius=1300;orbit.cursor.set(0,0,0);orbit.update();orbit.addEventListener('start',()=>{animation=null;});
 new ResizeObserver(resize).observe($('viewport'));resize();setSun(-50);
 renderer.domElement.addEventListener('webglcontextlost',event=>{event.preventDefault();toast('La vue 3D a été interrompue. Recharge la page pour la rétablir.');});
 let previousDown=null;renderer.domElement.addEventListener('pointerdown',e=>{previousDown={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(surveys?.interior||!previousDown||Math.hypot(e.clientX-previousDown.x,e.clientY-previousDown.y)>5)return;const rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(model.terrain,false)[0];if(!hit)return;if(placing){const spec=scenario.volumes.find(v=>v.id===volumeId);if(spec){spec.x=Number(hit.point.x.toFixed(2));spec.z=Number(hit.point.z.toFixed(2));refreshVolumes();placing=false;$('scene').classList.remove('placing');$('place-volume').textContent='Placer sur le terrain';toast('Position du volume mise à jour.');}}else{const p=data.parcels.find(p=>insidePolygons(hit.point.x,hit.point.z,p.polygons));selectParcel(p?.code||null,false);}});
 function frame(time){requestAnimationFrame(frame);if(document.hidden)return;if(animation){const t=Math.min(1,(time-animation.start)/1100),s=t*t*(3-2*t);camera.position.lerpVectors(animation.from,animation.to,s);orbit.target.lerpVectors(animation.tfrom,animation.tto,s);if(t===1)animation=null;}orbit.update();const min=model.height(camera.position.x,camera.position.z)+1.7;if(!surveys?.interior&&Number.isFinite(min)&&camera.position.y<min)camera.position.y=min;surveys?.update();renderer.render(scene,camera);}
 requestAnimationFrame(frame);$('loading').hidden=true;goView('castle');
 mountSurveys({scene,camera,orbit,renderer,model,cancelAnimation:()=>{animation=null;},toast}).then(value=>{surveys=value;}).catch(err=>{console.error(err);$('survey-status').textContent='Les relevés ne sont pas configurés. La maquette reste accessible.';});
}
function setSun(deg){if(!model)return;const a=deg*Math.PI/180,t=orbit?.target||new THREE.Vector3(model.castleData.center[0],3,model.castleData.center[1]);light.target.position.copy(t);light.position.set(t.x+Math.sin(a)*200,t.y+240,t.z+Math.cos(a)*200);light.shadow.needsUpdate=true;}

function syncVolumes(){if(!model)return;for(const o of [...model.projectGroup.children]){model.projectGroup.remove(o);o.geometry.dispose();o.material.dispose();}scenario.volumes.forEach(spec=>model.createVolume(spec));model.projectGroup.visible=$('show-project').checked;model.setFinishes(scenario.wall,scenario.roof,$('show-project').checked);}
function refreshVolumes(){syncVolumes();$('volume-list').replaceChildren();for(const v of scenario.volumes){const b=document.createElement('button');b.textContent=v.name;b.className=v.id===volumeId?'active':'';b.addEventListener('click',()=>{volumeId=v.id;refreshVolumes();const t=new THREE.Vector3(v.x,model.height(v.x,v.z)+v.height/2,v.z);animateCamera(t.clone().add(new THREE.Vector3(-25,25,38)),t);});$('volume-list').append(b);}const s=scenario.volumes.find(v=>v.id===volumeId);$('volume-editor').hidden=!s;if(s){for(const [field,key] of [['name','name'],['width','width'],['depth','depth'],['height','height'],['rotation','rotation']])$('volume-'+field).value=s[key];}}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function setUpControls(){
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>goView(b.dataset.view)));
 $('show-parcels').addEventListener('change',e=>{if(model)model.parcelGroup.visible=e.target.checked;if(!e.target.checked)selectParcel(null);});
 $('show-trees').addEventListener('change',e=>{if(surveys)surveys.setLayerVisible('trees',e.target.checked);else if(model)model.trees.visible=e.target.checked;});
 $('show-ortho').addEventListener('change',e=>{if(!model)return;model.terrainMaterial.map=e.target.checked?model.savedOrtho:null;model.terrainMaterial.color.set(e.target.checked?0xffffff:0x809563);model.terrainMaterial.needsUpdate=true;});
 $('deselect').addEventListener('click',()=>{selectParcel(null);goView('estate');});
 $('reset-view').addEventListener('click',()=>goView('castle'));
 $('zoom-in').addEventListener('click',()=>{if(!camera)return;camera.position.lerp(orbit.target,.18);orbit.update();});
 $('zoom-out').addEventListener('click',()=>{if(!camera)return;camera.position.add(camera.position.clone().sub(orbit.target).multiplyScalar(.22));orbit.update();});
 $('perspective-view').addEventListener('click',()=>goView(activeView));
 $('plan-view').addEventListener('click',()=>{if(!camera)return;const t=orbit.target.clone(),d=Math.max(100,camera.position.distanceTo(t));animateCamera(t.clone().add(new THREE.Vector3(0,d,.01)),t);plan=true;setProjectionButtons();$('scene-tag').textContent=selectedCode?'PLAN · PARCELLE '+selectedCode:'PLAN · NORD EN HAUT';});
 $('sun-angle').addEventListener('input',e=>setSun(Number(e.target.value)));
 $('capture').addEventListener('click',()=>{if(!renderer)return;renderer.render(scene,camera);renderer.domElement.toBlob(blob=>{if(blob)download(blob,'grangues-vue-3d.png');else toast('La capture n’a pas pu être créée.');});});
 $('about-button').addEventListener('click',()=>$('about-dialog').showModal());$('precision-button').addEventListener('click',()=>$('about-dialog').showModal());$('about-close').addEventListener('click',()=>$('about-dialog').close());$('photo-close').addEventListener('click',()=>$('photo-dialog').close());
 for(const id of ['about-dialog','photo-dialog'])$(id).addEventListener('click',e=>{if(e.target===$(id)){const r=$(id).getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$(id).close();}});
 $('error-references').addEventListener('click',()=>showTab('references'));
 $('add-volume').addEventListener('click',()=>{if(!model){toast('La vue 3D doit être disponible pour ajouter un volume.');return;}const local=model.castle.localToWorld(new THREE.Vector3(22,0,-18)),id=crypto.randomUUID();scenario.volumes.push({id,name:'Volume d’étude '+(scenario.volumes.length+1),x:Number(local.x.toFixed(2)),z:Number(local.z.toFixed(2)),width:8,depth:5,height:3,rotation:0});volumeId=id;refreshVolumes();const t=new THREE.Vector3(local.x,model.height(local.x,local.z),local.z);animateCamera(t.clone().add(new THREE.Vector3(-20,22,30)),t);});
 for(const key of ['name','width','depth','height','rotation'])$('volume-'+key).addEventListener('change',e=>{const spec=scenario.volumes.find(v=>v.id===volumeId);if(!spec)return;if(key==='name')spec.name=e.target.value.trim()||'Volume d’étude';else{const value=Number(e.target.value);if(!Number.isFinite(value))return;spec[key]=THREE.MathUtils.clamp(value,Number(e.target.min),Number(e.target.max));}refreshVolumes();});
 $('place-volume').addEventListener('click',()=>{placing=!placing;$('scene').classList.toggle('placing',placing);$('place-volume').textContent=placing?'Annuler le placement':'Placer sur le terrain';if(placing){toast('Clique sur le terrain à la position souhaitée.');if(matchMedia('(max-width:760px)').matches){$('sidebar').classList.add('closed');$('menu-toggle').setAttribute('aria-expanded','false');}}});
 $('remove-volume').addEventListener('click',()=>{scenario.volumes=scenario.volumes.filter(v=>v.id!==volumeId);volumeId=scenario.volumes[0]?.id||null;placing=false;$('scene').classList.remove('placing');refreshVolumes();});
 $('wall-finish').addEventListener('change',e=>{scenario.wall=e.target.value;syncVolumes();});$('roof-finish').addEventListener('change',e=>{scenario.roof=e.target.value;syncVolumes();});$('show-project').addEventListener('change',syncVolumes);
 $('save-project').addEventListener('click',()=>download(new Blob([JSON.stringify({...scenario,coordinateSystem:{crs:data.crs,origin:data.origin}},null,2)],{type:'application/json'}),'grangues-scenario.json'));
 $('load-project').addEventListener('click',()=>$('project-file').click());$('project-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1e6)throw new Error('Fichier trop volumineux.');const s=JSON.parse(await file.text());if(s.site!=='domaine-grangues-3d'||s.version!==1||!Array.isArray(s.volumes)||s.volumes.length>60)throw new Error('Ce fichier n’est pas un scénario de ce domaine.');for(const v of s.volumes)if(typeof v.name!=='string'||v.name.length>60||!['x','z','width','depth','height','rotation'].every(k=>Number.isFinite(v[k]))||v.width<1||v.width>100||v.depth<1||v.depth>100||v.height<.1||v.height>30||Math.abs(v.rotation)>360||v.x<data.bounds[0]||v.x>data.bounds[2]||v.z<data.bounds[1]||v.z>data.bounds[3])throw new Error('Le fichier contient un volume invalide.');if(!['existing','light','warm'].includes(s.wall)||!['existing','restored'].includes(s.roof))throw new Error('Matériaux inconnus.');scenario={version:1,site:'domaine-grangues-3d',wall:s.wall,roof:s.roof,volumes:s.volumes.map(v=>({...v,id:crypto.randomUUID()}))};volumeId=scenario.volumes[0]?.id||null;$('wall-finish').value=scenario.wall;$('roof-finish').value=scenario.roof;refreshVolumes();toast('Scénario chargé.');}catch(err){toast(err.message||'Ce scénario ne peut pas être ouvert.');}e.target.value='';});
 $('export-glb').addEventListener('click',async()=>{if(!model)return;surveys?.toModel();const b=$('export-glb');b.disabled=true;b.textContent='Préparation du fichier 3D…';toast('Création de la maquette 3D, cela peut prendre un moment.');try{const {GLTFExporter}=await import('./vendor/GLTFExporter.js');const result=await new GLTFExporter().parseAsync(model.root,{binary:true,onlyVisible:true,maxTextureSize:4096});download(new Blob([result],{type:'model/gltf-binary'}),'domaine-grangues-maquette.glb');toast('Maquette exportée dans les unités du projet : mètres.');}catch(err){console.error(err);toast('L’export 3D a échoué. Tu peux conserver le scénario en JSON.');}finally{b.disabled=false;b.textContent='Exporter la maquette 3D (.glb)';}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&placing){placing=false;$('scene').classList.remove('placing');$('place-volume').textContent='Placer sur le terrain';}});
}

async function start(){
 try{const result=await Promise.all([fetch('./assets/domain.json').then(r=>{if(!r.ok)throw new Error('Données du domaine absentes');return r.json();}),fetch('./assets/photos.json').then(r=>r.json())]);[data,photos]=result;initReferenceUi();setUpControls();const ortho=await loadTexture('./assets/ortho.jpg');setupScene(ortho);model.savedOrtho=ortho;}
 catch(err){console.error(err);$('loading').hidden=true;$('error').hidden=false;$('error-message').textContent='La maquette nécessite WebGL 2. Les photos et le plan restent accessibles dans Références. Si le problème persiste, essaie un autre navigateur.';if(!data)$('error-message').textContent='Les données du domaine n’ont pas pu être chargées. Recharge la page.';}
}
start();
